"""
Shared at-rest encryption utilities.

Used for two things in this codebase:
  1. Employee face photos in dataset/ (biometric data) - encrypted in place
     on disk, decrypted only in memory when actually needed (training,
     recognition, or serving a thumbnail to the admin UI).
  2. Optional per-employee custom payslip passwords (see pdf_generator.py /
     models.py) - stored encrypted rather than in plaintext, since (unlike
     login passwords) a PDF-open password must be recoverable in plaintext
     and therefore cannot simply be one-way hashed.

Key management
---------------
A single symmetric key (Fernet / AES-128-CBC + HMAC) is used for both.
The key is read from the FACE_DATA_ENCRYPTION_KEY environment variable
(normally set in .env, alongside SECRET_KEY / DB credentials - .env is
already gitignored in this project).

If no key is present - e.g. the very first time this runs after upgrading
an existing install - a new key is generated and appended to .env
automatically, and a loud warning is logged. This is a deliberate
"fail into a working, secure state" choice for a product installed by
non-technical small-business/student customers, who would otherwise be
stuck with an app that crashes on first run. The tradeoff to be aware of:
if .env is ever lost without a backup, previously-encrypted face images
and any custom payslip passwords become permanently unrecoverable (this is
inherent to encryption - there is no "forgot my key" recovery by design).
Back up .env the same way you'd back up the database.

IMPORTANT (PyInstaller): the .env this module reads from / writes to must
be resolved the SAME way config.py resolves BASE_DIR - i.e. next to the
.exe when frozen, NOT via this module's own `__file__`. In a frozen
PyInstaller onefile build, `__file__` for a module compiled into the
bundle resolves inside sys._MEIPASS, a temporary extraction folder that
is deleted on exit and recreated at a new random path on every launch.
If a generated key were ever appended to a `__file__`-derived path, it
would be written into that temp folder: the CURRENT process would still
work (the key is also set in os.environ for this run), but on the very
NEXT restart no key would be found in the real .env next to the exe, a
BRAND NEW key would be generated, and every previously-encrypted face
photo / payslip password would become permanently unreadable. Importing
BASE_DIR from config.py (rather than recomputing it from __file__ here)
is what avoids that.
"""
import os
import logging

from cryptography.fernet import Fernet, InvalidToken

from config import BASE_DIR

logger = logging.getLogger(__name__)

_ENV_KEY_NAME = "FACE_DATA_ENCRYPTION_KEY"
_fernet = None


def _env_file_path():
    # BASE_DIR comes from config.py, which is already frozen-aware:
    # the folder containing the .exe when packaged, or this project's
    # folder during normal `python app.py` development. Never derive
    # this from crypto_utils.py's own __file__ - see module docstring.
    return os.path.join(BASE_DIR, ".env")


def _persist_generated_key(key: str):
    """Append a freshly generated key to .env so it survives a restart."""
    env_path = _env_file_path()
    try:
        with open(env_path, "a", encoding="utf-8") as f:
            f.write(
                f"\n# Auto-generated by crypto_utils.py on first run - back this up.\n"
                f"{_ENV_KEY_NAME}={key}\n"
            )
        logger.warning(
            "No %s found in .env - generated a new encryption key and saved it "
            "to .env. BACK UP .env NOW: losing this key permanently locks you "
            "out of any previously-encrypted face photos / payslip passwords.",
            _ENV_KEY_NAME,
        )
    except OSError as e:
        logger.error(
            "Could not persist a generated %s to .env (%s). Set it manually as "
            "an environment variable, or encrypted data will not be readable "
            "again after this process restarts.",
            _ENV_KEY_NAME, e,
        )


def get_fernet() -> Fernet:
    """Return a process-wide Fernet instance, generating/persisting a key on first use."""
    global _fernet
    if _fernet is not None:
        return _fernet

    key = os.environ.get(_ENV_KEY_NAME)
    if not key:
        key = Fernet.generate_key().decode("utf-8")
        _persist_generated_key(key)
        os.environ[_ENV_KEY_NAME] = key

    _fernet = Fernet(key.encode("utf-8") if isinstance(key, str) else key)
    return _fernet


def encrypt_bytes(plaintext: bytes) -> bytes:
    """Encrypt raw bytes (e.g. a JPEG's contents) for storage on disk."""
    return get_fernet().encrypt(plaintext)


def decrypt_bytes(ciphertext: bytes) -> bytes:
    """Decrypt bytes previously produced by encrypt_bytes(). Raises InvalidToken on bad key/corrupt data."""
    return get_fernet().decrypt(ciphertext)


def encrypt_str(plaintext: str) -> str:
    """Encrypt a string (e.g. a custom payslip password) into a storable token string."""
    return get_fernet().encrypt(plaintext.encode("utf-8")).decode("utf-8")


def decrypt_str(token: str) -> str:
    """Decrypt a token string previously produced by encrypt_str()."""
    return get_fernet().decrypt(token.encode("utf-8")).decode("utf-8")


def is_encrypted(data: bytes) -> bool:
    """
    Best-effort check for whether `data` looks like a Fernet token, so
    callers can transparently support datasets that mix pre-existing
    plaintext images (captured before this feature was added) with newly
    captured encrypted ones, rather than requiring a one-shot migration.
    """
    try:
        # Fernet tokens are urlsafe-base64 and start with a fixed version
        # byte (0x80) once decoded; a real JPEG will fail this decode.
        get_fernet().decrypt(data)
        return True
    except InvalidToken:
        return False
    except Exception:
        return False
